// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Arc4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Arc6;
lv_obj_t * ui_Arc5;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;


// SCREEN: ui_Battery
void ui_Battery_screen_init(void);
void ui_event_Battery(lv_event_t * e);
lv_obj_t * ui_Battery;
lv_obj_t * ui_Arc3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label7;


// SCREEN: ui_List
void ui_List_screen_init(void);
void ui_event_List(lv_event_t * e);
lv_obj_t * ui_List;


// SCREEN: ui_Pulse
void ui_Pulse_screen_init(void);
void ui_event_Pulse(lv_event_t * e);
lv_obj_t * ui_Pulse;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Chart1;


// SCREEN: ui_Brightness
void ui_Brightness_screen_init(void);
void ui_event_Brightness(lv_event_t * e);
lv_obj_t * ui_Brightness;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Label4;


// SCREEN: ui_Time
void ui_Time_screen_init(void);
void ui_event_Time(lv_event_t * e);
lv_obj_t * ui_Time;
void ui_event_Spinbox2(lv_event_t * e);
lv_obj_t * ui_Spinbox2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1730909992[1] = {&ui_img_1111712444};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_List, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 350, 0, &ui_List_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Pulse, LV_SCR_LOAD_ANIM_MOVE_LEFT, 350, 0, &ui_Pulse_screen_init);
    }
}
void ui_event_Battery(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Home_screen_init);
    }
}
void ui_event_List(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Home_screen_init);
    }
}
void ui_event_Pulse(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Brightness, LV_SCR_LOAD_ANIM_MOVE_LEFT, 350, 0, &ui_Brightness_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 350, 0, &ui_Home_screen_init);
    }
}
void ui_event_Brightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_List, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_List_screen_init);
    }
}
void ui_event_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_List, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_List_screen_init);
    }
}
void ui_event_Spinbox2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_spinbox_step(ui_Spinbox2, 1);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_spinbox_step(ui_Spinbox2, -1);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Battery_screen_init();
    ui_List_screen_init();
    ui_Pulse_screen_init();
    ui_Brightness_screen_init();
    ui_Time_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
