// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#ifndef _SMARTWATCH_UI_UI_H
#define _SMARTWATCH_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Arc6;
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
// SCREEN: ui_Battery
void ui_Battery_screen_init(void);
void ui_event_Battery(lv_event_t * e);
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_List
void ui_List_screen_init(void);
void ui_event_List(lv_event_t * e);
extern lv_obj_t * ui_List;
// SCREEN: ui_Pulse
void ui_Pulse_screen_init(void);
void ui_event_Pulse(lv_event_t * e);
extern lv_obj_t * ui_Pulse;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Chart1;
// SCREEN: ui_Brightness
void ui_Brightness_screen_init(void);
void ui_event_Brightness(lv_event_t * e);
extern lv_obj_t * ui_Brightness;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Time
void ui_Time_screen_init(void);
void ui_event_Time(lv_event_t * e);
extern lv_obj_t * ui_Time;
void ui_event_Spinbox2(lv_event_t * e);
extern lv_obj_t * ui_Spinbox2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1111712444);    
LV_IMG_DECLARE(ui_img_calendar); 

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
