// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"
#include "../sensor_data/battery_gauge.h"

static void update_screen(){

    // Fetch battery data
    struct BatteryData battery_data = fetch_battery_data();

    // Update label
    char charge_str[5]; 
    snprintf(charge_str, sizeof(charge_str), "%d%%", battery_data.relative_state_of_charge);
	lv_label_set_text(ui_Label5, charge_str);

    // Update arc
    lv_arc_set_value(ui_Arc3, battery_data.relative_state_of_charge);
    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hsv_to_rgb(battery_data.relative_state_of_charge, 75, 100), LV_PART_INDICATOR | LV_STATE_DEFAULT);
}


// Event handler for the switch
static void event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        lv_obj_has_state(obj, LV_STATE_CHECKED) 
        ? lv_label_set_text(ui_Label7, " Power Saving | ON ") 
        : lv_label_set_text(ui_Label7, " Power Saving | OFF");
    }
}

void ui_Battery_screen_init(void)
{
    ui_Battery = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_Battery);
    lv_obj_set_width(ui_Arc3, 242);
    lv_obj_set_height(ui_Arc3, 242);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc3, 62);
    lv_arc_set_bg_angles(ui_Arc3, 270, 269);
    lv_obj_set_style_arc_width(ui_Arc3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0x40FF6C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_state(ui_Arc3, LV_STATE_DISABLED);

    ui_Label5 = lv_label_create(ui_Battery);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -41);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "58%");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Battery);
    lv_obj_set_width(ui_Switch1, 60);
    lv_obj_set_height(ui_Switch1, 30);
    lv_obj_set_x(ui_Switch1, 0);
    lv_obj_set_y(ui_Switch1, 60);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Switch1, event_handler, LV_EVENT_ALL, NULL);


    ui_Label7 = lv_label_create(ui_Battery);
    lv_obj_set_width(ui_Label7,  LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 14);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Power Saving | OFF");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Label7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Label7, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label7, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label7, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Battery, ui_event_Battery, LV_EVENT_ALL, NULL);

    lv_timer_create(update_screen, 1000, NULL); 

}
