// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"

void ui_exerciseMenu_screen_init(void)
{
    ui_exerciseMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_exerciseMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_exerciseMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_exerciseMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_exerciseMenu, ui_event_exerciseMenu, LV_EVENT_ALL, NULL);

}
