// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"

void ui_GpsTest_screen_init(void)
{
    ui_GpsTest = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GpsTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GpsTest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GpsTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_posLabel = lv_label_create(ui_GpsTest);
    lv_obj_set_width(ui_posLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_posLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_posLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_posLabel, "");
    lv_obj_set_style_text_font(ui_posLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_utcLabel = lv_label_create(ui_GpsTest);
    lv_obj_set_width(ui_utcLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_utcLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_utcLabel, 0);
    lv_obj_set_y(ui_utcLabel, 60);
    lv_obj_set_align(ui_utcLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_utcLabel, "12:53:24");
    lv_obj_set_style_text_font(ui_utcLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLabel = lv_label_create(ui_GpsTest);
    lv_obj_set_width(ui_statusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_statusLabel, 0);
    lv_obj_set_y(ui_statusLabel, -60);
    lv_obj_set_align(ui_statusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusLabel, "V");
    lv_obj_set_style_text_font(ui_statusLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_GpsTest, ui_event_GpsTest, LV_EVENT_ALL, NULL);

}
