// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"



static lv_obj_t * list1;

int scrolling = 0;


static void event_handler1(lv_event_t * e){
    printk("Released\n");
        //lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_STATE_DEFAULT);
        _ui_screen_change(&ui_Brightness, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, NULL);
}

static void event_handler2(lv_event_t * e){
    printk("Released\n");
        //lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_STATE_DEFAULT);
        _ui_screen_change(&ui_Brightness, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, NULL);
}

static void event_handler3(lv_event_t * e){
    printk("Released\n");
        //lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_STATE_DEFAULT);
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, NULL);
}

static void event_handler4(lv_event_t * e){
    printk("Released\n");
        //lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_STATE_DEFAULT);
        _ui_screen_change(&ui_Battery, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, NULL);
}


/*
static void event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);


    if (code == LV_EVENT_SCROLL_BEGIN) {
        scrolling = 1;
    } 
    if (code == LV_EVENT_SCROLL_END) {
        scrolling = 0;
    } 

    if(!scrolling){
        if (code == LV_EVENT_PRESSING) {
            printk("Pressing\n");
            //lv_obj_set_style_bg_opa(obj, LV_OPA_20, LV_STATE_DEFAULT);
        } 
        if (code == LV_EVENT_RELEASED) {
            printk("Released\n");
            //lv_obj_set_style_bg_opa(obj, LV_OPA_TRANSP, LV_STATE_DEFAULT);
            _ui_screen_change(&ui_Brightness, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, NULL);
        }
    }
    

}
*/




void ui_List_screen_init(void)
{
    ui_List = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_List, LV_OBJ_FLAG_SCROLLABLE);      

    
    //static lv_style_t style_screen;
    //lv_style_init(&style_screen);
    //lv_style_set_bg_color(&style_screen, lv_color_make(0, 0, 0)); 
    //lv_obj_add_style(ui_List, &style_screen, LV_PART_MAIN);

    
    static lv_style_t style_btn;
    lv_style_init(&style_btn);
    lv_style_set_radius(&style_btn, LV_RADIUS_CIRCLE);  
    lv_style_set_pad_all(&style_btn, 25); 
    lv_style_set_text_font(&style_btn, &lv_font_montserrat_16);
    lv_style_set_border_width(&style_btn, 0);
    lv_style_set_bg_color(&style_btn, lv_color_make(255, 255, 255)); 
    lv_style_set_bg_opa(&style_btn, LV_OPA_TRANSP);


    /*Create a list*/
    list1 = lv_list_create(ui_List);
    lv_obj_set_size(list1, 220, 240);
    lv_obj_center(list1);
    //lv_obj_add_event_cb(list1, event_handler, LV_EVENT_ALL, NULL);


    static lv_style_t style_list;
    lv_style_init(&style_list);
    lv_style_set_bg_color(&style_list, lv_color_make(0, 0, 0)); 
    lv_style_set_bg_opa(&style_list, LV_OPA_TRANSP);
    lv_style_set_border_width(&style_list, 0);
    lv_obj_add_style(list1, &style_list, LV_PART_MAIN);





    lv_obj_t * brightness_btn = lv_list_add_btn(list1, LV_SYMBOL_EYE_OPEN, "Brightness");
    lv_obj_add_event_cb(brightness_btn, event_handler1, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_style(brightness_btn, &style_btn, LV_PART_MAIN); 

    lv_obj_t * bluetooth_btn = lv_list_add_btn(list1, LV_SYMBOL_BLUETOOTH, "Bluetooth");
    lv_obj_add_event_cb(bluetooth_btn, event_handler2, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_style(bluetooth_btn, &style_btn, LV_PART_MAIN); 

    lv_obj_t * time_btn = lv_list_add_btn(list1, &ui_img_calendar, "Time & Date");
    lv_obj_add_event_cb(time_btn, event_handler3, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_style(time_btn, &style_btn, LV_PART_MAIN); 

    lv_obj_t * battery_btn = lv_list_add_btn(list1, LV_SYMBOL_BATTERY_2, "Battery");
    lv_obj_add_event_cb(battery_btn, event_handler4, LV_EVENT_SHORT_CLICKED, NULL);
    lv_obj_add_style(battery_btn, &style_btn, LV_PART_MAIN); 

     
    lv_obj_add_event_cb(ui_List, ui_event_List, LV_EVENT_ALL, NULL);
    

}
