// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"
#include "../../drivers/gnss/gnss.h"


static void toggle_gps(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        LV_UNUSED(obj);
        lv_obj_has_state(obj, LV_STATE_CHECKED) 
        ? exit_standby_mode()
        : enter_standby_mode();
    }
}

static void toggle_oximeter(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);
    printk("oximeter toggle\n");
}

void ui_powerManagment_screen_init(void)
{
    ui_powerManagment = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_powerManagment, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_powerManagment, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powerManagment, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_powerManagment);
    lv_obj_set_width(ui_Switch4, 50);
    lv_obj_set_height(ui_Switch4, 25);
    lv_obj_set_x(ui_Switch4, 0);
    lv_obj_set_y(ui_Switch4, -20);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Switch4, toggle_oximeter, LV_EVENT_ALL, NULL);


    ui_Switch5 = lv_switch_create(ui_powerManagment);
    lv_obj_set_width(ui_Switch5, 50);
    lv_obj_set_height(ui_Switch5, 25);
    lv_obj_set_x(ui_Switch5, 0);
    lv_obj_set_y(ui_Switch5, 70);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_Switch5, toggle_gps, LV_EVENT_ALL, NULL);


    ui_Label15 = lv_label_create(ui_powerManagment);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 2);
    lv_obj_set_y(ui_Label15, 28);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "GPS");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_powerManagment);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, -60);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Pulse Oximeter");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_powerManagment, ui_event_powerManagment, LV_EVENT_ALL, NULL);

}
