// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"

void ui_Time_screen_init(void)
{
    ui_Time = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinbox2 = lv_spinbox_create(ui_Time);
    lv_obj_set_width(ui_Spinbox2, 67);
    lv_obj_set_height(ui_Spinbox2, 58);
    lv_obj_set_x(ui_Spinbox2, 9);
    lv_obj_set_y(ui_Spinbox2, 3);
    lv_obj_set_align(ui_Spinbox2, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox2, 2, 0);
    lv_spinbox_set_range(ui_Spinbox2, 0, 24);
    lv_spinbox_set_step(ui_Spinbox2, round(pow(10, 1 - 1)));
    lv_spinbox_set_value(ui_Spinbox2, 19);

    lv_obj_add_event_cb(ui_Spinbox2, ui_event_Spinbox2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time, ui_event_Time, LV_EVENT_ALL, NULL);

}
