// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"

void ui_mainMenu_screen_init(void)
{
    ui_mainMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_mainMenu);
    lv_obj_set_width(ui_Arc1, 68);
    lv_obj_set_height(ui_Arc1, 68);
    lv_obj_set_x(ui_Arc1, 76);
    lv_obj_set_y(ui_Arc1, 22);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 100);
    lv_arc_set_bg_angles(ui_Arc1, 0, 360);
    lv_obj_set_style_arc_width(ui_Arc1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xA4A4A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_mainMenu);
    lv_obj_set_width(ui_Arc2, 68);
    lv_obj_set_height(ui_Arc2, 68);
    lv_obj_set_x(ui_Arc2, 0);
    lv_obj_set_y(ui_Arc2, 79);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc2, 100);
    lv_arc_set_bg_angles(ui_Arc2, 0, 360);
    lv_obj_set_style_arc_width(ui_Arc2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x7CFF9A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc4 = lv_arc_create(ui_mainMenu);
    lv_obj_set_width(ui_Arc4, 68);
    lv_obj_set_height(ui_Arc4, 68);
    lv_obj_set_x(ui_Arc4, -46);
    lv_obj_set_y(ui_Arc4, -64);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc4, 100);
    lv_arc_set_bg_angles(ui_Arc4, 0, 360);
    lv_obj_set_style_arc_width(ui_Arc4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x628EFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc5 = lv_arc_create(ui_mainMenu);
    lv_obj_set_width(ui_Arc5, 68);
    lv_obj_set_height(ui_Arc5, 68);
    lv_obj_set_x(ui_Arc5, -76);
    lv_obj_set_y(ui_Arc5, 22);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc5, 100);
    lv_arc_set_bg_angles(ui_Arc5, 0, 360);
    lv_obj_set_style_arc_width(ui_Arc5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0xFF4B4B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc6 = lv_arc_create(ui_mainMenu);
    lv_obj_set_width(ui_Arc6, 68);
    lv_obj_set_height(ui_Arc6, 68);
    lv_obj_set_x(ui_Arc6, 46);
    lv_obj_set_y(ui_Arc6, -64);
    lv_obj_set_align(ui_Arc6, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc6, 100);
    lv_arc_set_bg_angles(ui_Arc6, 0, 360);
    lv_obj_set_style_arc_width(ui_Arc6, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc6, lv_color_hex(0xFF40FA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc6, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc6, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc6, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_mainMenu);
    lv_img_set_src(ui_Image3, &ui_img_exercise1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_Image3, 46);
    lv_obj_set_y(ui_Image3, -64);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_mainMenu);
    lv_img_set_src(ui_Image4, &ui_img_headphones_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_Image4, -46);
    lv_obj_set_y(ui_Image4, -64);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_mainMenu);
    lv_img_set_src(ui_Image5, &ui_img_heart_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_Image5, -76);
    lv_obj_set_y(ui_Image5, 22);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_mainMenu);
    lv_img_set_src(ui_Image6, &ui_img_settings_icon_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_Image6, 76);
    lv_obj_set_y(ui_Image6, 22);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_mainMenu);
    lv_img_set_src(ui_Image8, &ui_img_battery_full_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 79);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_mainMenu, ui_event_mainMenu, LV_EVENT_ALL, NULL);

}
