// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: smartwatch_ui

#include "ui.h"


void list_item_click_event(lv_obj_t * obj, lv_event_t event) {
    
}


void ui_settingsMenu_screen_init(void)
{
    ui_settingsMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingsMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_settingsMenu, ui_event_settingsMenu, LV_EVENT_ALL, NULL);


    //lv_obj_t *cont = lv_obj_create(ui_settingsMenu );
    //lv_obj_set_size(cont, 210, 240); 

    lv_obj_t *list = lv_list_create(ui_settingsMenu);
    lv_obj_set_size(list, 210, 240); 
    lv_obj_align(list, LV_ALIGN_CENTER, 0, 0);



    // Bluetooth Button -----------------------------------------------------------------------------------------------------

    lv_obj_t *bluetooth_btn = lv_list_add_btn(list, NULL, NULL);
    lv_obj_align(bluetooth_btn, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_width(bluetooth_btn, 210);
    lv_obj_set_height(bluetooth_btn, 75);

    lv_obj_t *bluetooth_container = lv_obj_create(bluetooth_btn);
    lv_obj_align(bluetooth_container, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_width(bluetooth_container, 210);
    lv_obj_set_height(bluetooth_container, 75);
    
    lv_obj_t *bluetooth_label = lv_label_create(bluetooth_container);
    lv_label_set_text(bluetooth_label, "Bluetooth");
    lv_obj_set_style_text_font(bluetooth_label, &lv_font_montserrat_20, NULL);
    lv_obj_align(bluetooth_label, LV_ALIGN_RIGHT_MID, 0, 0);

    lv_obj_t * bluetooth_icon_container = lv_obj_create(bluetooth_container);
    lv_obj_set_width(bluetooth_icon_container, 50);
    lv_obj_set_height(bluetooth_icon_container, 50);
    lv_obj_set_align(bluetooth_icon_container, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_border_color(bluetooth_icon_container, lv_color_hex(0xFF40FA), NULL);
    lv_obj_set_style_border_width(bluetooth_icon_container, 3, NULL);
    lv_obj_set_style_radius(bluetooth_icon_container, 100, NULL);
    lv_obj_set_style_bg_color(bluetooth_icon_container, lv_color_hex(0xFF40FA), NULL);
    lv_obj_set_style_bg_opa(bluetooth_icon_container, 15, NULL);
    lv_obj_set_style_shadow_color(bluetooth_icon_container, lv_color_hex(0xFF40FA), NULL);
    lv_obj_set_style_shadow_opa(bluetooth_icon_container, 255, NULL);
    lv_obj_set_style_shadow_width(bluetooth_icon_container, 25, NULL);
    lv_obj_set_style_shadow_spread(bluetooth_icon_container, 1, NULL);

    //lv_obj_add_event_cb(bluetoothButton, button_event_handler, LV_EVENT_ALL, NULL);




    // Battery Button -----------------------------------------------------------------------------------------------------

    lv_obj_t *battery_btn = lv_list_add_btn(list, NULL, NULL); // Use NULL for empty text

    lv_obj_t *battery_container = lv_obj_create(battery_btn);

    lv_obj_set_width(battery_container, 210);
    lv_obj_set_height(battery_container, 75);
    
    lv_obj_t *battery_label = lv_label_create(battery_container);
    lv_label_set_text(battery_label, "Battery");
    lv_obj_set_style_text_font(battery_label, &lv_font_montserrat_20, NULL);
    lv_obj_align(battery_label, LV_ALIGN_CENTER, 0, 0);
    
    lv_obj_t * battery_icon_container = lv_obj_create(battery_container);
    lv_obj_set_width(battery_icon_container, 50);
    lv_obj_set_height(battery_icon_container, 50);
    lv_obj_set_align(battery_icon_container, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_border_color(battery_icon_container, lv_color_hex(0x7CFF9A), NULL);
    lv_obj_set_style_border_width(battery_icon_container, 3, NULL);
    lv_obj_set_style_radius(battery_icon_container, 100, NULL);
    lv_obj_set_style_bg_color(battery_icon_container, lv_color_hex(0x7CFF9A), NULL);
    lv_obj_set_style_bg_opa(battery_icon_container, 15, NULL);
    lv_obj_set_style_shadow_color(battery_icon_container, lv_color_hex(0x7CFF9A), NULL);
    lv_obj_set_style_shadow_opa(battery_icon_container, 255, NULL);
    lv_obj_set_style_shadow_width(battery_icon_container, 25, NULL);
    lv_obj_set_style_shadow_spread(battery_icon_container, 1, NULL);

    //lv_obj_add_event_cb(batteryButton, button_event_handler, LV_EVENT_ALL, NULL);


    // Time Zone Button -----------------------------------------------------------------------------------------------------

    lv_obj_t *time_zone_btn = lv_list_add_btn(list, NULL, NULL); // Use NULL for empty text
    lv_obj_set_width(time_zone_btn, 210);
    lv_obj_set_height(time_zone_btn, 75);

    lv_obj_t *time_zone_container = lv_obj_create(time_zone_btn);
    lv_obj_set_width(time_zone_container, 210);
    lv_obj_set_height(time_zone_container, 75);
    lv_obj_align_to(time_zone_container, NULL, LV_ALIGN_LEFT_MID, 0, 0);
    lv_obj_set_style_bg_color(time_zone_container, lv_color_white(), NULL);
    
    lv_obj_t *time_zone_label = lv_label_create(time_zone_container);
    lv_label_set_text(time_zone_label, "Time Zone");
    lv_obj_set_style_text_font(time_zone_label, &lv_font_montserrat_20, NULL);
    lv_obj_align(time_zone_label, LV_ALIGN_CENTER, 0, 0);
    
    lv_obj_t * time_zone_icon_container = lv_obj_create(time_zone_container);
    lv_obj_set_width(time_zone_icon_container, 50);
    lv_obj_set_height(time_zone_icon_container, 50);
    lv_obj_set_align(time_zone_icon_container, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_border_color(time_zone_icon_container, lv_color_hex(0x628EFF), NULL);
    lv_obj_set_style_border_width(time_zone_icon_container, 3, NULL);
    lv_obj_set_style_radius(time_zone_icon_container, 100, NULL);
    lv_obj_set_style_bg_color(time_zone_icon_container, lv_color_hex(0x628EFF), NULL);
    lv_obj_set_style_bg_opa(time_zone_icon_container, 15, NULL);
    lv_obj_set_style_shadow_color(time_zone_icon_container, lv_color_hex(0x628EFF), NULL);
    lv_obj_set_style_shadow_opa(time_zone_icon_container, 255, NULL);
    lv_obj_set_style_shadow_width(time_zone_icon_container, 25, NULL);
    lv_obj_set_style_shadow_spread(time_zone_icon_container, 1, NULL);

    //lv_obj_add_event_cb(batteryButton, button_event_handler, LV_EVENT_ALL, NULL);




 

}
